import type { Metadata } from "next";
import { Nunito, Inter } from "next/font/google";
import "./globals.css";

// RoadHome fonts
const nunito = Nunito({
  variable: "--font-display",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${inter.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
